'use client';
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/W7SI7A7i5Mi
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useState } from 'react';
import { sleep } from '@/lib/utils';

export function ForgotPassword() {
  const [loading, setLoading] = useState(false);
  const [showError, setShowError] = useState(false);
  const [value, setValue] = useState('');

  return (
    <div className='flex min-h-screen items-center'>
      <div className='mx-auto max-w-md space-y-6 py-12'>
        <div className='space-y-2 text-center'>
          <h1 className='text-3xl font-bold'>Forgot Password</h1>
          <p className='text-muted-foreground'>
            Enter your email address below and we'll send you a link to reset your password.
          </p>
        </div>
        <Card>
          <CardContent className='space-y-4'>
            <div className='space-y-2'>
              <Label htmlFor='email'>Email</Label>
              <Input
                value={value}
                onChange={e => setValue(e.target.value)}
                id='email'
                type='email'
                placeholder='m@example.com'
                required
              />
              {showError && <p className='text-sm text-destructive'>Your email is not correct.</p>}
            </div>
            <Button
              disabled={loading}
              type='submit'
              className='w-full'
              onClick={async () => {
                setLoading(true);
                await sleep();
                try {
                  await fetch('/api/v1/forgot-password', {
                    method: 'POST',
                    body: JSON.stringify({
                      email: value,
                    }),
                  });
                } catch {}
                setLoading(false);
                setShowError(true);
              }}
            >
              Reset Password
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
